# Generated by Django 2.2.5 on 2019-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Posted_date',
            field=models.TimeField(),
        ),
    ]
