# Generated by Django 2.2.5 on 2019-10-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20191014_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtiming',
            name='Timing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Posted_date',
            field=models.DateField(),
        ),
    ]
