# Generated by Django 2.2.5 on 2019-10-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20191014_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='SubDate',
            field=models.CharField(max_length=10),
        ),
    ]
