# Generated by Django 2.2.5 on 2019-10-13 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20191014_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='SubDate',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Submission_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
