# Generated by Django 2.2.5 on 2019-10-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20191014_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtiming',
            name='Timing',
            field=models.DateTimeField(),
        ),
    ]
